@extends('layouts.main')

@section('title', 'Chi siamo')

@section('content')
    <h2>Chi siamo?</h2>

    <h3>La vera storia della creazione di Booflix che nessuno conosce</h3>

    <p>
        Il “mito” della fondazione di Netflix risale a metà degli anni Novanta, quando Reed Hastings, uno dei due creatori, si è trovato a dover pagare alla cassa di un Blockbuster una penale di 40 dollari per aver restituito in ritardo la videocassetta di Apollo 13. In seguito allo spiacevole episodio, l’attuale presidente del colosso dello streaming ha iniziato a riflettere sulle possibilità offerte dal mercato dei DVD, in ascesa e ancora poco occupato da potenziali competitor. Nella realtà dei fatti, la nascita di Netflix non fu esattamente frutto di un colpo di genio, come ha raccontato Marc Randolph, l’altro fondatore, in un libro di recente pubblicazione, That will Never work (Non funzionerà mai. La nascita di Netflix e la straordinaria vita di un'idea). Il divertente memoir restituisce il clima pionieristico degli anni d'oro della Silicon Valley offrendo anche spunti di educazione imprenditoriale per startupper in erba.
    </p>

    <p>
        Nella primavera del 1997 la prima idea di business di Reed e Marc fu quella del noleggio di videogiochi e di film in DVD tramite posta: bastava collegarsi al sito di NetFlix (rigorosamente con la F maiuscola), scegliere il titolo ed attendere il postino. Il tutto per 6 dollari, comprese le spese di spedizione. “Per capire se potesse funzionare abbiamo testato il meccanismo in prima persona,” racconta Randolph nel libro. “Abbiamo infilato un CD in una busta con un francobollo da 32 centesimi e l’abbiamo spedito a casa di Reed. Il giorno dopo aveva ricevuto il CD integro ed è stato allora che abbiamo capito di poter andare avanti”. La formula, però, stentava a decollare, così Hastings decise di passare all’abbonamento mensile senza limiti: si potevano scegliere fino a un massimo di 3 titoli, restituirli e riceverne altri anche più volte nello stesso mese. La prima sede di Netflix era un vecchio ufficio di una banca a Santa Cruz, in California, il cui caveau era utilizzato per archiviare e catalogare tutti i DVD.
    </p>

    <p>
        Il primo “testimonial” del progetto fu inconsapevolmente l’ex presidente degli Stati Uniti, Bill Clinton, a cui è legato un aneddoto che, a distanza di decenni, fa ancora scappare un sorriso al fondatore e primo ceo di Netflix. “Nel 1998 si parlava solo del Sexgate. Noi eravamo una piccola startup che non poteva permettersi grandi investimenti per una campagna di marketing e allora abbiamo deciso di utilizzare lo scandalo Clinton-Lewinsky a nostro vantaggio,” continua Randolph. “Il piano era di far pagare ai clienti 2 centesimi di dollaro per un DVD contenente le quattro ore di testimonianza al Congresso da parte del presidente. Dopo aver spedito cinquemila dischi, alcuni nostri abbonati ci hanno detto di aver ricevuto un film per adulti e non il processo Clinton: il produttore ci aveva dato uno stock sbagliato non contrassegnato. Il giorno dopo abbiamo inviato una lettera di scuse, dicendo che se avessero voluto avrebbero potuto rispedirci a nostre spese il DVD sbagliato. Non l’ha fatto nessuno”.
    </p>

    <p>
        Tra le pagine del suo manifesto imprenditoriale, l’ex ceo spiega anche il significato del cosiddetto “principio del Canada”, invocato dai vertici ogniqualvolta il progetto sembrava allontanarsi dall’obiettivo principale. Venne coniato nelle prime fasi dello sviluppo del piano strategico, ovvero quando si decise di non spedire i DVD nel vicino Canada. Lo sforzo logistico sarebbe stato controproducente a causa della differenza di valuta. Il principio, vero e proprio mantra salva-sprechi della società, ha influito più avanti sulla decisione di escludere dal noleggio i non abbonati e, anche oggi, sulla riluttanza nel cedere i diritti esclusivi dei film originali Netflix ai principali gruppi di sale cinematografiche: una mossa che, in occasione della proiezione di The Irishman di Martin Scorsese, ha portato grandi guadagni sia all’azienda che alle piccole sale indipendenti che hanno fatto da vetrina alla pellicola tre settimane prima dell’uscita sulla piattaforma digitale.
    </p>

    <p>
        In un altro capitolo di That will Never work Randolph racconta il giorno della quotazione a Wall Street, uno spartiacque per la società, vissuto tutto sommato senza grandi festeggiamenti dai suoi creatori: “Come la maggior parte delle aziende tecnologiche, abbiamo debuttato sul Nasdaq, un indice completamente elettronico. Nessun trading floor né operatori isterici al telefono. Ci siamo goduti il primo scambio in una grande sala piena di scrivanie della banca Merrill Lynch. Il ricordo più bello? A fine giornata, quando per molti versi la nostra idea era diventata la nostra ragione di vita, sono andato a mangiare una pizza con mio figlio Logan”.
    </p>

    <p>
        Randolph lasciò Netflix nel 2003, quattro anni prima che lo streaming rappresentasse la svolta dell’azienda californiana. Le ultime mosse del duo al comando furono il rifiuto categorico della “cannibalizzazione” da parte di Amazon di Jeff Bezos e un incontro con John Antioco, ceo di Blockbuster, organizzato per proporre una sinergia volta a coprire le mancanze “digitali” dell’ex colosso del videonoleggio. Le risposte non furono quelle che Hastings e il suo socio si aspettavano: Antioco parlò di “isteria del dot com”, deridendo il web e le sue potenzialità e declinando un’offerta di acquisizione per 50 milioni, le perdite di Netflix in quel momento. Una cifra che considerò “ridicola”. Sliding doors che furono fatali per Blockbuster che, dilaniato dai costi fissi dei negozi fisici e dall’obsolescenza del DVD, dichiarò il fallimento qualche anno dopo. La crescita del colosso dell’intrattenimento, invece, ha cambiato il nostro modo di vedere film e serie tv, arrivando a sfiorare i 200 milioni di abbonati e i 20 miliardi di dollari di fatturato e mettendo a disposizione non solo una piattaforma di distribuzione online curata nei minimi dettagli, ma anche un modello produttivo basato sui dati di consumo dei clienti al pari di Google e Facebook. La forza di Netflix è la capacità di costruire una sensazione di sicurezza intorno ai suoi utenti che alla fine di una visione, grazie al sofisticato algoritmo celato dietro la semplice interfaccia, sono invogliati ad iniziarne un’altra in linea con il loro gusto: la base del cosiddetto binge-watching.
    </p>

    <p>
        Oggi Randolph non ha più alcun rapporto con Netflix. Possiede ancora alcune azioni, “per motivi sentimentali”, come lui stesso confessa nel libro, e paga una quota di abbonamento mensile come tutti. Dalla sua uscita societaria nel 2003 ha fondato una decina di altre start-up, ha fatto da mentore a imprenditori emergenti e ha investito in numerose compagnie tech ora affermate. Tra i motivi del successo dell’impero di Hastings mette al primo posto la cultura aziendale informale che responsabilizza i collaboratori invece di controllarli, un valore aggiunto a cui lui stesso ha contribuito agli albori assieme a Patty McCord, responsabile delle Risorse Umane di Netflix fino al 2013. Gli 8600 dipendenti di Los Gatos si valutano a vicenda, sono incoraggiati a prendere parte nelle decisioni strategiche e sono liberi di gestire le proprie ferie, mentre le informazioni sugli stipendi sono trasparenti. Nell’agosto del 2009 Netflix decise di rendere pubblico il suo regolamento interno con una presentazione in PowerPoint di 125 slide: con 20 milioni di visualizzazioni su SlideShare, Freedom and Responsibility è ancora oggi uno dei manifesti più importanti della Silicon Valley. Così come l’ultima fatica letteraria di Marc Randolph, una preziosa eredità per chiunque voglia fare business: “Ci sarà sempre qualcuno che ti dirà che la tua idea non funzionerà. Per svilupparla bisogna dedicarle la vita, ma lascia che siano gli altri a metterci i soldi. Coinvolgere altri investitori, oltre a famiglia e amici, ti costringe a dimostrare che la tua folle idea potrebbe funzionare davvero”.
    </p>
    @endsection